title: Прикласительный на свадьбу Алексей и Алёна 24.08.2026
description: Да, я развернул его на своём гитхабе, потому что так было проще всего. Да, домен странный, ну извините! Это логин моего гитхаба. Я его создавал на первом курсе универа и не думал что он будет потом использован как ссылка на приглаистельный на мою свадьбу. Буэ XD
